data:
  raw_data_file: "../data/raw/train.csv"
  preprocessed_data_file: "../data/preprocessed/preprocessed_data.csv"
  processed_data_file: "../data/processed/processed_data.csv"
  test_data_file: "../data/final/test.csv"
  output_dir: "output/"
  categorical_features: []
  continuous_features: []
  y_names: []

training:
  valid_pct: 0.2
  seed: 42
  layers: [200, 100]
  metrics: [accuracy]
  epochs: 10
  batch_size: 64
  models_dir: "../models/"
